import { StyleSheet } from 'react-native';

const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
    },
    appBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fef7ff',
        paddingVertical: 8,
        paddingHorizontal: 4,
        width: '100%',
        height: 48,
    },
    appBarHeadline: {
        fontSize: 22,
        lineHeight: 28,
        fontWeight: '400',
        fontFamily: 'Roboto',
        color: '#1d1b20',
        textAlign: 'center',
        flex: 1,
    },
    appBarIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#6d4cce',
        justifyContent: 'center',
        alignItems: 'center',
    },
    appBarIcon: {
        width: 24,
        height: 24,
    },
    textFieldContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e6e0e9',
        paddingVertical: 4,
        paddingHorizontal: 16,
        width: '100%',
        height: 70,
    },
    textFieldContentContainer: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        paddingVertical: 8,
    },
    textFieldLabel: {
        fontFamily: 'Roboto',
        fontWeight: '400',
        fontSize: 12,
        letterSpacing: 0.4,
        color: '#49454f',
        marginBottom: 4,
    },
    textFieldInput: {
        fontFamily: 'Roboto',
        fontWeight: '400',
        fontSize: 16,
        letterSpacing: 0.5,
        color: '#1d1b20',
        lineHeight: 24,
    },
    textFieldIconContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#fff',
    },
    textFieldIcon: {
        width: 24,
        height: 24,
    },
    joinButton: {
        backgroundColor: '#65558F',
        borderRadius: 100,
        width: '100%',
        height: 66,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 24,
        flexDirection: 'row',
    },
    joinButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '500',
        lineHeight: 20,
        letterSpacing: 0.1,
        textAlign: 'center',
    },
    createButton: {
        backgroundColor: '#65558F',
        paddingVertical: 14.5,
        paddingHorizontal: 24,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: 66,
    },
    createButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '500',
        letterSpacing: 0.1,
        textAlign: 'center',
        lineHeight: 20,
    },
    space: {
        height: 32,
    },
    spaceSmall: {
        height: 16,
    }
});

export default homeStyles;
